Fashion Fiesta/MVC_Project/MVC_Project/Controllers/DressesController.cs
using MVC_Project.Models;
using MVC_Project.Models.View_Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Project.Controllers
{
    [Authorize]
    public class DressesController : Controller
    {
        
        FashionFiestaDbContext db = new FashionFiestaDbContext();
        // GET: Dresses
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public PartialViewResult DressInfo(int page = 1)
        {
            var data = db.Dresses.Include(x => x.Stocks)
                                 .Include(x => x.DressCategory)
                                 .Include(x => x.Brand)
                                 .OrderBy(x => x.DressID)
                                 .ToPagedList(page, 5);
            return PartialView("_DressInfo", data);
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult CreateForm()
        {
            DressInputModel inputModel = new DressInputModel();
            inputModel.Stocks.Add(new Stock());
            ViewBag.DressCategory = db.DressCategories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            return PartialView("_CreateForm",inputModel);
        }
        [HttpPost]
        public ActionResult Create(DressInputModel inputModel, string act = "")
        {
            if (act == "add")
            {
                inputModel.Stocks.Add(new Stock());
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                inputModel.Stocks.RemoveAt(index);
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act == "insert")
            {
                if (ModelState.IsValid)
                {
                    var dress = new Dress
                    {
                        Name = inputModel.Name,
                        LaunchDate = inputModel.LaunchDate,
                        DressCategoryID = inputModel.DressCategoryID,
                        BrandID = inputModel.BrandID,
                        SaleStatus = inputModel.SaleStatus
                    };
                    //For Image Save
                    string ext = Path.GetExtension(inputModel.Picture.FileName);
                    string file = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                    string savePath = Path.Combine(Server.MapPath("~/Images"), file);
                    inputModel.Picture.SaveAs(savePath);
                    dress.Picture = file;

                    db.Dresses.Add(dress);
                    db.SaveChanges();
                    //Stocks
                    foreach (var s in inputModel.Stocks)
                    {
                        db.Database.ExecuteSqlCommand($"spInsertStock {(int)s.Size},{s.Price},{(int)s.Quantity},{dress.DressID}");
                    }
                    DressInputModel newModel = new DressInputModel()
                    {
                        Name = "",
                        LaunchDate = DateTime.Today
                    };
                    newModel.Stocks.Add(new Stock());

                    ViewBag.DressCategory = db.DressCategories.ToList();
                    ViewBag.Brands = db.Brands.ToList();
                    foreach (var e in ModelState.Values)
                    {
                        e.Value = null;
                    }
                    return View("_CreateForm", newModel);
                }
            }
            ViewBag.DressCategory = db.DressCategories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            return View("_CreateForm", inputModel);
        }
        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        public ActionResult EditForm(int id)
        {
            var data = db.Dresses.FirstOrDefault(x => x.DressID == id);
            if (data == null) return new HttpNotFoundResult();
            db.Entry(data).Collection(x => x.Stocks).Load();
            DressEditModel model = new DressEditModel
            {
                DressID = id,
                BrandID = data.BrandID,
                DressCategoryID = data.DressCategoryID,
                Name = data.Name,
                LaunchDate = data.LaunchDate,
                SaleStatus = data.SaleStatus,
                Stocks = data.Stocks.ToList()
            };
            ViewBag.DressCategory = db.DressCategories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            ViewBag.CurrentPic = data.Picture;
            return PartialView("_EditForm", model);
        }

        [HttpPost]
        public ActionResult Edit(DressEditModel editModel, string act = "")
        {
            if (act == "add")
            {
                editModel.Stocks.Add(new Stock());
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                editModel.Stocks.RemoveAt(index);
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act == "update")
            {
                if (ModelState.IsValid)
                {
                    var dress = db.Dresses.FirstOrDefault(x => x.DressID == editModel.DressID);
                    if (dress == null) { return new HttpNotFoundResult(); }
                    dress.Name = editModel.Name;
                    dress.LaunchDate = editModel.LaunchDate;
                    dress.SaleStatus = editModel.SaleStatus;
                    dress.BrandID = editModel.BrandID;
                    dress.DressCategoryID = editModel.DressCategoryID;
                    if (editModel.Picture != null)
                    {
                        string ext = Path.GetExtension(editModel.Picture.FileName);
                        string file = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                        string savePath = Path.Combine(Server.MapPath("~/Images"), file);
                        editModel.Picture.SaveAs(savePath);
                        dress.Picture = file;
                    }
                    else
                    {

                    }
                    db.SaveChanges();
                    db.Database.ExecuteSqlCommand($"EXEC spDeleteStock {dress.DressID}");
                    foreach (var d in editModel.Stocks)
                    {
                        db.Database.ExecuteSqlCommand($"EXEC spInsertStock {(int)d.Size}, {d.Price}, {d.Quantity}, {dress.DressID}");
                    }
                }
            }
            ViewBag.DressCategory = db.DressCategories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            ViewBag.CurrentPic = db.Dresses.FirstOrDefault(x => x.DressID == editModel.DressID)?.Picture;
            return View("_EditForm", editModel);
        }

        public ActionResult Delete(int? id)
        {
            var dress = db.Dresses.Find(id);
            if(dress != null)
            {
                var deleteStock = db.Stocks.Where(x => x.DressID == id).ToList();
                db.Stocks.RemoveRange(deleteStock);
                db.Dresses.Remove(dress);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Fashion Fiesta/MVC_Project/MVC_Project/Views/Dresses/Create.cshtml
@{
    ViewBag.Title = "Create";
}
<style>
    body {
        background-color: paleturquoise;
    }
</style>
<div class="row">
    <div class="col">
        <div id="form-div">
            @Html.Action("CreateForm")
        </div>
    </div>
</div>

Fashion Fiesta/MVC_Project/MVC_Project/Views/Dresses/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}
<style>
    body {
        background-color: cornsilk;
    }
</style>
<div class="row">
    <div class="col">
        <div id="form-div">
            @Html.Action("EditForm")
        </div>
    </div>
</div>

Fashion Fiesta/MVC_Project/MVC_Project/Views/Dresses/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<style>
    body {
        background-image: url("/Images/Brandslogo.jpg");
    }
</style>
<h2 class="display-4 text-decoration-underline text-center">Dress Information</h2>

<div class="row">
    <div class="col">
        <div class="d-flex justify-content-end">
            <a href="@Url.Action("Create","Dresses")" class="btn btn-outline-dark"><i class="fa fa-plus-square"></i> Add New Dress</a>
        </div>
    </div>
    <div id="table-div">
        @Html.Action("DressInfo")
    </div>
</div>

@section styles{
    <!-- Option 1: Include in HTML -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
}
@section scripts{
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    <script>
        $(document).on("click", "button.show", function () {
            var showBtn = $(this);
            var hideBtn = showBtn.next();
            var trSh = showBtn.closest("tr");
            var trSt = trSh.next();
            showBtn.hide();
            hideBtn.show();
            trSt.show();
        });
        $(document).on("click", "button.hide", function () {
            var hideBtn = $(this);
            var showBtn = hideBtn.prev();
            var trSh = showBtn.closest("tr");
            var trSt = trSh.next();
            showBtn.show();
            hideBtn.hide();
            trSt.hide();
        });
    </script>
}

Fashion Fiesta/MVC_Project/MVC_Project/Views/Dresses/_CreateForm.cshtml
@model MVC_Project.Models.View_Models.DressInputModel

@using (Ajax.BeginForm("Create", "Dresses", new { }, new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "form-div",
    OnSuccess = "OnSuccess"
}, new { id = "frm", enctype = "multipart/form-data" }))
{
    <h2 class="display-4 text-decoration-underline">Add New Dress</h2>
    <div class="row mb-2">
        @Html.LabelFor(x => x.BrandID, new { @class = "col-form-label col-2 " })
        <div class="col-6">
            @Html.DropDownListFor(x => x.BrandID, new SelectList(ViewBag.Brands, "BrandID", "BrandName"), "-Select One-", new { @class = "form-select" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.BrandID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.DressCategoryID, new { @class = "col-form-label col-2 " })
        <div class="col-6">
            @Html.DropDownListFor(x => x.DressCategoryID, new SelectList(ViewBag.DressCategory, "DressCategoryID", "CategoryName"), "-Select One-", new { @class = "form-select" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.DressCategoryID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.Name, new { @class = "col-form-label col-2 " })
        <div class="col-6">
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.LaunchDate, new { @class = "col-form-label col-2 " })
        <div class="col-6">
            @Html.TextBoxFor(x => x.LaunchDate, new { @class = "form-control", type = "date", @value = DateTime.Today.ToString("yyyy-MM-dd") })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.LaunchDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-2 " })
        <div class="col-6">
            @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-10 offset-2">
            <div class="form-check">
                <label>
                    Available?
                </label>
                @Html.CheckBoxFor(x => x.SaleStatus)
            </div>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-8">
            <div class="d-flex justify-content-between">
                <h3 class="display-5 text-decoration-underline">Stocks</h3>
                <button class="btn btn-dark btn-sm" type="submit" name="act" value="add" formnovalidate>Add</button>
            </div>
            <table class="table table-bordered table-sm">
                <thead class="table-dark">
                    <tr>
                        <th>Size</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Stocks.Count; i++)
                    {
                        <tr>
                            <td>
                                @Html.EnumDropDownListFor(x => Model.Stocks[i].Size, new { @class = "form-select" })
                                @Html.ValidationMessageFor(x => Model.Stocks[i].Size, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.Stocks[i].Price, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.Stocks[i].Price, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.Stocks[i].Quantity, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.Stocks[i].Quantity, "", new { @class = "text-danger" })
                            </td>
                            <td class="text-center">
                                <button name="act" value="remove_@i" type="submit" class="btn btn-danger btn-sm" formnovalidate>Remove</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-6">
            <button type="submit" name="act" value="insert" class="btn btn-outline-dark"><i class="fa fa-save"></i> Submit</button>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Fashion Fiesta/MVC_Project/MVC_Project/Views/Dresses/_DressInfo.cshtml
@model IEnumerable<MVC_Project.Models.Dress>
@using PagedList
@using PagedList.Mvc


<table class="table table-bordered table-striped table-hover table-sm mt-2">
    <thead class="table-dark">
        <tr class="text-center">
            <th></th>
            <th></th>
            <th>Brand</th>
            <th>Category</th>
            <th>Name</th>
            <th>Arrival Date</th>
            <th>Available?</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var d in Model)
        {
            <tr class="text-center">
                <td style="width:40px;text-align:center;">
                    <button type="button" class="btn btn-sm show"><i class="bi bi-chevron-right"></i></button>
                    <button type="button" class="btn btn-sm hide" style="display:none;"><i class="bi bi-chevron-up"></i></button>
                </td>
                <td style="width:50px; text-align:center">
                    <img src="~/Images/@d.Picture" class="fa-square" style="width:40px;" />
                </td>
                <td>@d.Brand.BrandName</td>
                <td>@d.DressCategory.CategoryName</td>
                <td>@d.Name</td>
                <td>@d.LaunchDate.ToString("yyyy-MM-dd")</td>
                <td>@(d.SaleStatus?"Yes":"No")</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Dresses", new { id = d.DressID }, new { @class = "btn btn-success btn-sm" })
                    @Html.ActionLink("Delete", "Delete", "Dresses", new { id = d.DressID }, new { @class = "btn btn-danger btn-sm" })
                </td>
            </tr>
            <tr style="display:none;">
                <td></td>
                <td colspan="8">
                    <h4>Stocks</h4>
                    <table class="table table-bordered table-striped table-striped">
                        <thead class="table-secondary">
                            <tr class="text-center">
                                <th>Size</th>
                                <th>Price</th>
                                <th>Quantity</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var t in d.Stocks)
                            {
                                <tr class="text-center">
                                    <td>@t.Size</td>
                                    <td>@t.Price</td>
                                    <td>@t.Quantity</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </td>
            </tr>
        }
    </tbody>
</table>

Fashion Fiesta/MVC_Project/MVC_Project/Views/Dresses/_EditForm.cshtml
@model MVC_Project.Models.View_Models.DressEditModel

@using (Ajax.BeginForm("Edit", "Dresses", new { }, new AjaxOptions
{
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "form-div"
},
 new { id = "frm", enctype = "multipart/form-data" }))
{
    <h2 class="display-4 text-decoration-underline">Edit Dress</h2>
    <div class="row mb-2">
        @Html.HiddenFor(x => x.DressID)
        @Html.HiddenFor(x => x.Picture)
        @Html.LabelFor(x => x.BrandID, new { @class = "col-form-label col-2 " })
        <div class="col-6">
            @Html.DropDownListFor(x => x.BrandID, new SelectList(ViewBag.Brands, "BrandID", "BrandName"), "---Select---", new { @class = "form-select" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.BrandID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.DressCategoryID, new { @class = "col-form-label col-2 " })
        <div class="col-6">
            @Html.DropDownListFor(x => x.DressCategoryID, new SelectList(ViewBag.DressCategory, "DressCategoryID", "CategoryName"), "---Select---", new { @class = "form-select" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.DressCategoryID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.Name, new { @class = "col-form-label col-2 " })
        <div class="col-6">
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.LaunchDate, new { @class = "col-form-label col-2 " })
        <div class="col-6">
            @Html.EditorFor(x => x.LaunchDate, new {htmlAttibutes= new { @class = "form-control", type="date" }} )
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.LaunchDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-2 " })
        <div class="col-6">
            @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
            @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
            <div class="col-6">
                <img src="~/Images/@ViewBag.CurrentPic" style="width:200px;" class="img-thumbnail" />
            </div>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-10 offset-2">
            <div class="form-check">
                @Html.CheckBoxFor(x => x.SaleStatus)
                <label>
                    Avaiable??
                </label>
            </div>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-6">
            <div class="d-flex justify-content-between">
                <h3 class="display-5 text-decoration-underline">Stocks</h3>
                <button class="btn btn-dark btn-sm" type="submit" name="act" value="add" formnovalidate>Add</button>
            </div>
            <table class="table table-bordered table-sm">
                <thead class="table-dark">
                    <tr>
                        <th>Size</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Stocks.Count; i++)
                    {
                        <tr>
                            <td>
                                @Html.EnumDropDownListFor(x => Model.Stocks[i].Size, new { @class = "form-select" })
                                @Html.ValidationMessageFor(x => Model.Stocks[i].Size, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.Stocks[i].Price, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.Stocks[i].Price, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.Stocks[i].Quantity, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.Stocks[i].Quantity, "", new { @class = "text-danger" })
                            </td>
                            <td class="text-center">
                                <button name="act" value="remove_@i" type="submit" class="btn btn-danger btn-sm" formnovalidate>Remove</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-6">
            <button type="submit" name="act" value="update" class="btn btn-outline-dark"><i class="fa fa-save"></i>Update</button>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>