Fashion Fiesta/MVC_Project/MVC_Project/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_Project.Models;

namespace MVC_Project.Controllers
{
    public class BrandsController : Controller
    {
        private FashionFiestaDbContext db = new FashionFiestaDbContext();

        public ActionResult Index()
        {
            return View(db.Brands.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BrandID,BrandName")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Brands.Add(brand);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(brand);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BrandID,BrandName")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brand).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Brand brand = db.Brands.Find(id);
            db.Brands.Remove(brand);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Fashion Fiesta/MVC_Project/MVC_Project/Controllers/DressCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_Project.Models;

namespace MVC_Project.Controllers
{
    public class DressCategoriesController : Controller
    {
        private FashionFiestaDbContext db = new FashionFiestaDbContext();


        public ActionResult Index()
        {
            return View(db.DressCategories.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DressCategoryID,CategoryName")] DressCategory dressCategory)
        {
            if (ModelState.IsValid)
            {
                db.DressCategories.Add(dressCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dressCategory);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DressCategory dressCategory = db.DressCategories.Find(id);
            if (dressCategory == null)
            {
                return HttpNotFound();
            }
            return View(dressCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DressCategoryID,CategoryName")] DressCategory dressCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dressCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dressCategory);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DressCategory dressCategory = db.DressCategories.Find(id);
            if (dressCategory == null)
            {
                return HttpNotFound();
            }
            return View(dressCategory);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DressCategory dressCategory = db.DressCategories.Find(id);
            db.DressCategories.Remove(dressCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Fashion Fiesta/MVC_Project/MVC_Project/Views/DressCategories/Create.cshtml
@model MVC_Project.Models.DressCategory

@{
    ViewBag.Title = "Create";
}
<style>
    body {
        background-color: gainsboro;
    }
</style>
<h2 class="display-4 text-decoration-underline">Add New Category</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row mb-2">
                @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-8">
                    @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="col-2">
                    @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-10 offset-2">
                <input type="submit" value="Save" class="btn btn-dark" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Fashion Fiesta/MVC_Project/MVC_Project/Views/DressCategories/Delete.cshtml
@model MVC_Project.Models.DressCategory

@{
    ViewBag.Title = "Delete";
}
<style>
    body {
        background-color: gainsboro;
    }
</style>
<h2 class="display-4 text-decoration-underline">Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.CategoryName)</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Html.DisplayFor(model => model.CategoryName)</td>
                <td>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div>
                            <input type="submit" value="Delete" class="btn btn-danger" />
                        </div>
                    }
                </td>
            </tr>
        </tbody>
    </table>
    @Html.ActionLink("Back to List", "Index")
</div>

Fashion Fiesta/MVC_Project/MVC_Project/Views/DressCategories/Edit.cshtml
@model MVC_Project.Models.DressCategory

@{
    ViewBag.Title = "Edit";
}
<style>
    body {
        background-color: gainsboro;
    }
</style>
<h2>Update Category</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row mb-2">
                @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-8">
                    @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="col-2">
                    @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-10 offset-2">
                <input type="submit" value="Update" class="btn btn-dark" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Fashion Fiesta/MVC_Project/MVC_Project/Views/DressCategories/Index.cshtml
@model IEnumerable<MVC_Project.Models.DressCategory>

@{
    ViewBag.Title = "Index";
}
<style>
    body {
        background-image: url("/Images/Brandslogo.jpg");
    }
</style>
<h2 class="display-4 text-decoration-underline">Category List</h2>

<p class="d-flex justify-content-end">
    <a href="@Url.Action("Create","DressCategories")" class="btn btn-outline-dark"><i class="fa fa-plus-square"></i> Add New Brand</a>

</p>
<table class="table table-bordered table-striped table-hover">
    <thead class="text-center">
        <tr>
            <th>Category Name</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoryName)
                </td>
                <td class="text-center">
                    <a href="@Url.Action("Edit", "Brands", new {id=item.DressCategoryID})" class="btn btn-success btn-sm">Edit</a> |
                    <a href="@Url.Action("Delete", "Brands", new {id=item.DressCategoryID})" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>